id: I1A434AA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:55:34+00:00'
last_modified: '2022-06-08T04:36:59.445100+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18072
  title: དུས་འབྲེལ་གསོ་སྦྱོང་ཚོགས་པའི་ཉི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A9AE:
      image_group_id: I8LS18112
      title: ''
      total_pages: 66
      order: 1
      base_file: A9AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
