id: P004447
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:22:39.762398
source_metadata:
  id: bdr:W8LS18072
  title: དུས་འབྲེལ་གསོ་སྦྱོང་ཚོགས་པའི་ཉི་མ།
  author: ''
  volumes:
    546f1bb624c54e9f90e7ab510e1435a4:
      image_group_id: I8LS18112
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
